name: practice hosted runner
env:
  Message:
on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  runner_practice:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
      - run: echo practice for runner
      - name: Run a multi-line script
      - run: |
        echo need to do practice for it
        echo this is for practice purpose