name: practice hosted runner
env:
  Message: "i'm akash user"
on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: Run a one-line script
        run: echo $Message
      - name: Run a multi-line script
        run: 
          echo need to do practice for it,
          echo this is for practice purpose